apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
  labels:
    app: myapp
spec:
  replicas: 2   # Number of pods (replica set)
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-container
          image: bruacr.azurecr.io/brihatthi:v1  # <-- Replace with your Docker image
          ports:
            - containerPort: 8000
          
