apiVersion: v1
kind: Service
metadata:
  name: my-svc
  labels:
    app: myapp
spec:
  type: ClusterIP   # Can change to ClusterIP or LoadBalancer
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 8000          # Service port
      targetPort: 8000    # Container port
